### ISSUE TITLE
How to Calculate F-Score for Voxels?

### ISSUE THREAD

**Issue by hzxie** [lmb-freiburg/what3d#1]
The code provides the code for calculating F-Score for point clouds, but not for Voxels.
Could you provide the code for calculating F-Score for voxels?

I cannot understand how to calculate F-Score for voxels after reading your paper.
Thanks.

**Comment by tatarchm** [comment]
Done, please see the instructions in the updated README.

**Comment by hzxie** [comment]
But you didn't add the code for sampling points from meshes.

**Comment by tatarchm** [comment]
There are built-in Open3D functions for this [http://www.open3d.org/docs/release/python_api/open3d.geometry.TriangleMesh.html](). You can use `sample_points_poisson_disk` or `sample_points_uniformly`.

**Comment by hzxie** [comment]
I suggest you to add the code to repository.
Thank you.
